{ config, lib, ... }:
let
  service = "ntfy";
  cfg = config.homelab.services.${service};
  hl = config.homelab;
  port = 2586;
in
{
  options.homelab.services.${service} = {
    enable = lib.mkEnableOption {
      description = "Enable ${service}";
    };
    url = lib.mkOption {
      type = lib.types.str;
      default = "ntfy.${hl.baseDomain}";
    };
    monitoredServices = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "ntfy-sh" ];
    };
    environmentFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Environment file holding the secret half of the declarative auth
        provisioning: NTFY_AUTH_USERS (user:bcrypt-hash:role) and
        NTFY_AUTH_TOKENS (user:token[:label]).
      '';
      example = lib.literalExpression ''
        pkgs.writeText "ntfy-envfile" '''
          NTFY_AUTH_USERS=phil:$2a$10$REPLACE_WITH_BCRYPT_HASH:admin
          NTFY_AUTH_TOKENS=phil:tk_REPLACE_WITH_TOKEN:Nextcloud
        '''
      '';
    };
  };
  config = lib.mkIf cfg.enable {
    services.ntfy-sh = {
      enable = true;
      settings = {
        base-url = "https://${cfg.url}";
        listen-http = "127.0.0.1:${toString port}";
        # Without this, every request appears to come from nginx
        # (127.0.0.1) and all clients share a single visitor's rate
        # limits (60-request burst, 30 subscriptions) — which starves
        # Synapse's pushes and the phones' UnifiedPush streams.
        behind-proxy = true;
        auth-file = "/var/lib/ntfy-sh/user.db";
        auth-default-access = "deny-all";
        # UnifiedPush topics (up*) are anonymously readable and writable:
        # homeservers push via the built-in Matrix gateway and phones
        # subscribe without an account. The random ~12-char topic name
        # generated by the ntfy app is the access secret (capability-URL
        # model); every other topic stays deny-all.
        auth-access = [ "everyone:up*:read-write" ];
      };
    };

    systemd.services.ntfy-sh.serviceConfig.EnvironmentFile =
      lib.mkIf (cfg.environmentFile != null) [ cfg.environmentFile ];

    services.nginx.virtualHosts."${cfg.url}" = {
      forceSSL = true;
      enableACME = false;
      sslCertificate = "/var/lib/acme/${hl.baseDomain}/fullchain.pem";
      sslCertificateKey = "/var/lib/acme/${hl.baseDomain}/key.pem";
      extraConfig = ''
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
      '';
      locations."/" = {
        proxyPass = "http://127.0.0.1:${toString port}";
        extraConfig = ''
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 3600;
          keepalive_timeout 3600;
        '';
      };
    };
  };
}
